### ISSUE TITLE
Parties

### ISSUE THREAD

**Issue by Benjamin-Catinella** [Benjamin-Catinella/SQ_Mobile#22]
- [ ] Page statique
- [ ] Liste dynamique des parties en cours
- [ ] Continuer une partie
- [ ] Quitter une partie
